-- Sinh tự động từ src/data/products.json + src/data/productDetails.js
-- Chạy SAU khi đã chạy schema.sql và rls-policies.sql.

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'magie-bo-kem-no1', 'Magie Bo Kẽm No.1', 'phan-bon-la', '["lua","rau-mau","cay-an-trai","hoa-kieng","cay-cong-nghiep"]'::jsonb, 'Gói 500g', 'bot', 72000, null,
  '/products/cards/magie-bo-kem-no1-card.png', '["/products/magie-bo-kem-no1/img-1.png","/products/magie-bo-kem-no1/img-2.jpg","/products/magie-bo-kem-no1/img-3.jpg","/products/magie-bo-kem-no1/img-4.jpg","/products/magie-bo-kem-no1/img-5.jpg","/products/magie-bo-kem-no1/img-6.jpg","/products/magie-bo-kem-no1/img-7.jpg","/products/magie-bo-kem-no1/img-8.jpg"]'::jsonb, 'Phân bón lá trung vi lượng giúp lớn trái, đẹp màu, ra rễ mạnh và xanh dày lá.', 'Magie (Mg) 0,48%; Bo (B) 500ppm; Kẽm (Zn) 5.000ppm; Sắt (Fe) 10.000ppm; Mangan (Mn) 5.000ppm; pH H2O: 5; Độ ẩm: 5%', 'Cây lương thực: 10-20g/bình 10 lít hoặc 10-20ml/bình 8 lít. Rau màu: 5-10g/bình 8 lít. Cây ăn quả & cây công nghiệp: 10-20g/bình 8 lít. Hoa kiểng: 5-10g/bình 8 lít. Phun định kỳ 7-10 ngày/lần, liều lượng điều chỉnh theo hiện trạng cây trồng, mùa vụ và đất đai.', '["ra-re","xanh-la","nuoi-trai","phuc-hoi-cay-yeu"]'::jsonb, '["ban-chay"]'::jsonb, false,
  'Magie Bo Kẽm No.1 là phân bón lá trung vi lượng dạng bột hòa tan, hỗ trợ cây trồng bổ sung các nguyên tố vi lượng thiết yếu như Magie, Bo, Kẽm, Sắt và Mangan — những yếu tố đóng vai trò quan trọng trong quá trình sinh trưởng, ra hoa, đậu trái và tạo màu sắc trái.

Sản phẩm phù hợp cho nhiều nhóm cây trồng, đặc biệt trong các giai đoạn cây ra hoa, đậu trái, phát triển lá non và khi cây có biểu hiện thiếu vi lượng như lá vàng, trái nhỏ, đọt xoắn hoặc lá mỏng nhạt màu.', '[{"label":"Magie (Mg)","value":"0,48%"},{"label":"Bo (B)","value":"500 ppm"},{"label":"Kẽm (Zn)","value":"5.000 ppm"},{"label":"Sắt (Fe)","value":"10.000 ppm"},{"label":"Mangan (Mn)","value":"5.000 ppm"},{"label":"pH H₂O","value":"5"},{"label":"Độ ẩm","value":"5%"}]'::jsonb, 'Thông tin thành phần được trình bày theo công bố trên bao bì sản phẩm.', '["Hỗ trợ lớn trái, đẹp màu và cải thiện chất lượng quả.","Góp phần kích thích để nhánh, sai hoa và đậu trái nhiều hơn.","Giúp chồi lá mập, hạn chế hiện tượng đọt xoắn và chùn đọt.","Hỗ trợ lá xanh dày, mượt lá và tăng khả năng quang hợp.","Góp phần kích thích ra rễ và phát triển bộ rễ khỏe mạnh.","Hỗ trợ cây phục hồi trong giai đoạn thiếu vi lượng hoặc sau stress."]'::jsonb, '["Pha Magie Bo Kẽm No.1 với nước sạch theo liều lượng khuyến cáo trên bao bì.","Lắc hoặc khuấy đều dung dịch trước khi phun.","Phun đều lên mặt lá, mặt dưới lá và phần ngọn cây vào buổi sáng sớm hoặc chiều mát.","Phun định kỳ 7–10 ngày/lần hoặc điều chỉnh theo tình trạng cây thực tế.","Tránh phun khi trời mưa, nắng gắt hoặc nhiệt độ quá cao trong ngày."]'::jsonb, '[{"crop":"Cây lương thực","dosage":"10–20g / bình 10 lít"},{"crop":"Rau màu","dosage":"5–10g / bình 8 lít"},{"crop":"Cây ăn quả & cây công nghiệp","dosage":"10–20g / bình 8 lít"},{"crop":"Hoa kiểng","dosage":"5–10g / bình 8 lít"}]'::jsonb,
  '["Bảo quản nơi khô ráo, thoáng mát.","Tránh ánh nắng trực tiếp.","Đậy kín nắp sau khi mở hoặc sau khi sử dụng.","Không để sản phẩm tiếp xúc trực tiếp với nước khi chưa pha.","Để xa tầm tay trẻ em và vật nuôi.","Không bảo quản gần thực phẩm, nguồn nước sinh hoạt hoặc hóa chất không tương thích."]'::jsonb, 'Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"Mg, Bo, Kẽm, Fe, Mn","xuatXu":"Việt Nam","dang":"Bột hòa tan","congDung":"Lớn trái, đẹp màu, ra rễ","baoQuan":"Nơi khô ráo, thoáng mát"}'::jsonb, '[{"icon":"Leaf","title":"Lá xanh dày, mượt lá","text":"Hỗ trợ bổ sung Magie và vi lượng giúp lá xanh dày, mượt và tăng hiệu quả quang hợp."},{"icon":"Sun","title":"Lớn trái, đẹp màu","text":"Góp phần cải thiện kích thước, màu sắc và chất lượng trái thông qua bổ sung Kẽm và Bo."},{"icon":"Sprout","title":"Ra rễ, đẻ nhánh","text":"Hỗ trợ phát triển bộ rễ và kích thích đẻ nhánh, sai hoa trong giai đoạn sinh trưởng."},{"icon":"Shield","title":"Hạn chế thiếu vi lượng","text":"Phù hợp khi cây có dấu hiệu đọt xoắn, chùn đọt, vàng lá hoặc thiếu khoáng vi lượng."}]'::jsonb, '[{"icon":"AlertCircle","title":"Cây có đọt xoắn","desc":"Hỗ trợ khi cây có hiện tượng đọt xoắn hoặc chùn đọt do thiếu vi lượng."},{"icon":"Leaf","title":"Lá vàng, bạc màu","desc":"Phù hợp khi lá cây có dấu hiệu vàng nhạt hoặc thiếu dinh dưỡng vi lượng."},{"icon":"Sun","title":"Trái nhỏ, màu nhạt","desc":"Hỗ trợ giai đoạn nuôi trái khi trái chậm lớn hoặc màu sắc chưa đẹp."},{"icon":"Sprout","title":"Cây ít hoa, đậu ít","desc":"Phù hợp khi cây ra hoa kém hoặc tỉ lệ đậu trái thấp hơn bình thường."},{"icon":"Zap","title":"Sau giai đoạn stress","desc":"Giúp bổ sung vi lượng cho cây sau thời kỳ chịu hạn, ngập hoặc sâu bệnh."}]'::jsonb, '{"nhomSanPham":"Phân bón lá","quyCach":"Gói 500g","dangSanPham":"Bột hòa tan","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'ph-balance-humate-79', 'pH Balance - Humate 79 Grown', 'phan-bon-re', '["lua","rau-mau","cay-an-trai","hoa-kieng","cay-cong-nghiep"]'::jsonb, 'Hũ 1kg', 'hat', 127000, null,
  '/products/cards/ph-balance-humate-79-card.png', '["/products/ph-balance-humate-79/gallery/img-1.png","/products/ph-balance-humate-79/gallery/img-2.png","/products/ph-balance-humate-79/gallery/img-3.png","/products/ph-balance-humate-79/gallery/img-4.png","/products/ph-balance-humate-79/gallery/img-5.png","/products/ph-balance-humate-79/gallery/img-6.png","/products/ph-balance-humate-79/gallery/img-7.png","/products/ph-balance-humate-79/gallery/img-8.png","/products/ph-balance-humate-79/gallery/img-9.png","/products/ph-balance-humate-79/gallery/img-10.png"]'::jsonb, 'Phân bón sinh học nâng pH, cải tạo đất, kích thích ra rễ và phục hồi cây sau thu hoạch.', 'Axit Humic (C): 22,6%; pH H2O: 5; Độ ẩm: 30%', 'Pha loãng theo hướng dẫn trên bao bì, tưới gốc hoặc phun định kỳ để nâng pH, cân bằng pH đất, cải tạo đất, kích thích bộ rễ phát triển và phục hồi cây sau thu hoạch.', '["ra-re","cai-tao-dat","phuc-hoi-cay-yeu"]'::jsonb, '["moi","ban-chay"]'::jsonb, true,
  'pH Balance - Humate 79 Grown là sản phẩm phân bón sinh học hỗ trợ nâng pH đất, cải tạo đất và kích thích bộ rễ phát triển. Sản phẩm phù hợp cho nhiều nhóm cây trồng, đặc biệt trong các trường hợp đất có dấu hiệu chai cứng, cây sinh trưởng kém hoặc cần phục hồi sau thu hoạch.

Với thành phần Axit Humic 22,6%, sản phẩm góp phần cải thiện cấu trúc đất, hỗ trợ trao đổi dinh dưỡng và tăng khả năng hấp thu của bộ rễ trong nhiều điều kiện đất và loại cây khác nhau.', '[{"label":"Axit Humic (C)","value":"22,6%"},{"label":"pH H₂O","value":"5"},{"label":"Độ ẩm","value":"30%"}]'::jsonb, 'Thông tin thành phần được trình bày theo công bố trên bao bì sản phẩm.', '["Hỗ trợ nâng pH và cân bằng môi trường đất phù hợp cho cây trồng.","Góp phần cải tạo đất, hỗ trợ đất tơi xốp và thông thoáng hơn.","Kích thích phát triển rễ non, rễ tơ và tăng diện tích hấp thu của bộ rễ.","Hỗ trợ nhú đọt, ra chồi nhanh và phát đọt mạnh trong giai đoạn sinh trưởng.","Góp phần phục hồi cây sau thu hoạch hoặc sau giai đoạn suy yếu.","Hỗ trợ tăng sức đề kháng tự nhiên của cây trồng."]'::jsonb, '["Pha loãng pH Balance - Humate 79 Grown với nước tưới theo hướng dẫn trên bao bì.","Tưới đều quanh vùng gốc hoặc khu vực rễ hoạt động của cây.","Sử dụng định kỳ tùy theo tình trạng đất và giai đoạn sinh trưởng của cây.","Nên tưới vào buổi sáng sớm hoặc chiều mát để tránh bay hơi nhanh.","Có thể phối hợp với quy trình chăm sóc đất hiện tại theo hướng dẫn kỹ thuật."]'::jsonb, null,
  '["Đậy kín nắp sau khi sử dụng để giữ chất lượng sản phẩm.","Bảo quản nơi khô ráo, thoáng mát.","Tránh ánh nắng trực tiếp.","Đậy kín nắp sau khi mở hoặc sau khi sử dụng.","Không để sản phẩm tiếp xúc trực tiếp với nước khi chưa pha.","Để xa tầm tay trẻ em và vật nuôi.","Không bảo quản gần thực phẩm, nguồn nước sinh hoạt hoặc hóa chất không tương thích."]'::jsonb, 'Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"Axit Humic 22,6%","xuatXu":"Việt Nam","dang":"Sinh học (hạt)","congDung":"Cải tạo đất, hỗ trợ ra rễ","baoQuan":"Nơi khô ráo, thoáng mát"}'::jsonb, '[{"icon":"Sprout","title":"Hỗ trợ cải tạo đất","text":"Góp phần làm đất tơi xốp, thông thoáng và thuận lợi hơn cho rễ phát triển."},{"icon":"Leaf","title":"Kích thích phát triển rễ","text":"Hỗ trợ rễ non, rễ tơ và tăng khả năng hấp thu dinh dưỡng của bộ rễ."},{"icon":"Shield","title":"Hỗ trợ phục hồi cây","text":"Phù hợp cho cây sau thu hoạch hoặc cây suy yếu do điều kiện canh tác."},{"icon":"Zap","title":"Dễ kết hợp quy trình","text":"Có thể dùng trong nhiều giai đoạn tùy theo loại cây và hướng dẫn sử dụng."}]'::jsonb, '[{"icon":"AlertCircle","title":"Đất chai, bạc màu","desc":"Hỗ trợ cải thiện độ tơi xốp và môi trường đất quanh vùng rễ."},{"icon":"Sprout","title":"Cây yếu rễ","desc":"Phù hợp khi cây có bộ rễ kém phát triển hoặc hấp thu dinh dưỡng yếu."},{"icon":"Leaf","title":"Cây chậm phục hồi","desc":"Hỗ trợ cây trong giai đoạn phục hồi chậm sau stress hoặc sâu bệnh."},{"icon":"Sun","title":"Sau thu hoạch","desc":"Phù hợp cho cây sau vụ thu hoạch, hỗ trợ phục hồi và chuẩn bị vụ tiếp theo."},{"icon":"Zap","title":"Hấp thu kém","desc":"Góp phần cải thiện khả năng hấp thu khi đất có pH chưa phù hợp."}]'::jsonb, '{"nhomSanPham":"Phân bón rễ / Sinh học","quyCach":"Hũ 1kg","dangSanPham":"Sinh học (hạt)","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'ra-re-no-bui', 'Ra Rễ - Nở Bụi', 'phan-bon-re', '["lua"]'::jsonb, 'Chai 250ml', 'nuoc', 90000, null,
  '/products/cards/ra-re-no-bui-card.png', '["/products/ra-re-no-bui/gallery/img-1.png","/products/ra-re-no-bui/gallery/img-2.png","/products/ra-re-no-bui/gallery/img-3.png","/products/ra-re-no-bui/gallery/img-4.png","/products/ra-re-no-bui/gallery/img-5.png","/products/ra-re-no-bui/gallery/img-6.png","/products/ra-re-no-bui/gallery/img-7.png","/products/ra-re-no-bui/gallery/img-8.png","/products/ra-re-no-bui/gallery/img-9.png","/products/ra-re-no-bui/gallery/img-10.png","/products/ra-re-no-bui/gallery/img-11.png","/products/ra-re-no-bui/gallery/img-12.png","/products/ra-re-no-bui/gallery/img-13.png","/products/ra-re-no-bui/gallery/img-14.png","/products/ra-re-no-bui/gallery/img-15.png"]'::jsonb, 'Phân bón NPK 10-4-4 chuyên dùng cho lúa, giúp ra rễ mạnh, nở bụi nhanh, cứng cây, hạn chế phèn mặn.', 'Đạm tổng số (N): 10%; Lân hữu hiệu (P2O5): 4%; Kali hữu hiệu (K2O): 4%; Độ ẩm: 5%; Tỷ trọng (dạng lỏng): 1,1', 'Cây ăn trái & cây công nghiệp: 0,5-0,8 lít/500 lít nước/1.000m², tưới gốc 3-4 lần/năm vào giai đoạn phát triển thân lá, ra hoa, đậu quả và sau thu hoạch. Rau màu & cây lương thực: 0,5-0,8 lít/550 lít nước/1.000m², tưới gốc 3 đợt: 10-15, 25-30 và 40-45 ngày sau gieo sạ. Ngưng bón trước thu hoạch 5-7 ngày.', '["ra-re","cai-tao-dat","xanh-la"]'::jsonb, '["ban-chay"]'::jsonb, true,
  'Ra Rễ - Nở Bụi là phân bón NPK 10-4-4 dạng lỏng, chuyên dùng cho cây lúa. Sản phẩm hỗ trợ ra rễ mạnh, đẻ nhánh nhanh, cứng cây và giúp cây lúa hấp thu dinh dưỡng hiệu quả hơn trong giai đoạn đầu sinh trưởng.

Sản phẩm sử dụng nguyên liệu ngoại nhập, được pha chế phù hợp với đặc điểm đất và khí hậu Việt Nam. Phù hợp cho các vùng đất phèn, mặn hoặc khi bộ rễ cây lúa cần được kích thích phục hồi và phát triển.', '[{"label":"Đạm tổng số (N)","value":"10%"},{"label":"Lân hữu hiệu (P₂O₅)","value":"4%"},{"label":"Kali hữu hiệu (K₂O)","value":"4%"},{"label":"Độ ẩm (dạng rắn)","value":"5%"},{"label":"Tỷ trọng (dạng lỏng)","value":"1,1"}]'::jsonb, 'Phân bón NPK 10-4-4 K4P. Sử dụng nguyên liệu ngoại nhập.', '["Hỗ trợ lúa ra rễ mạnh và phục hồi bộ rễ bị tổn thương trong đất phèn mặn.","Góp phần kích thích đẻ nhánh nhanh, nở bụi sớm và cứng cây.","Hỗ trợ giải độc hữu cơ và giảm thiểu ảnh hưởng của phèn mặn.","Giúp cân bằng pH trong điều kiện đất phèn hoặc nhiễm mặn.","Hỗ trợ dòng mạp, trổ tập trung và vào gạo nhanh hơn.","Giúp lá lúa xanh mướt, hạn chế vàng lá và sinh trưởng đồng đều."]'::jsonb, '["Lắc đều chai Ra Rễ - Nở Bụi trước khi sử dụng.","Pha với nước tưới theo tỉ lệ khuyến cáo trên bao bì sản phẩm.","Tưới đều vào gốc và vùng rễ hoạt động của cây lúa.","Áp dụng đúng giai đoạn (xem bảng liều lượng phía dưới) để đạt hiệu quả tốt nhất.","Ngừng sử dụng trước thu hoạch ít nhất 5–7 ngày."]'::jsonb, '[{"crop":"Cây ăn trái & cây công nghiệp","dosage":"0,5–0,8 lít / 500 lít nước / 1.000m², tưới 3–4 lần/năm"},{"crop":"Rau màu & cây lương thực","dosage":"0,5–0,8 lít / 550 lít nước / 1.000m², tưới 3 đợt: 10–15, 25–30 và 40–45 ngày sau sạ"}]'::jsonb,
  '["Bảo quản nơi khô ráo, thoáng mát.","Tránh ánh nắng trực tiếp.","Đậy kín nắp sau khi mở hoặc sau khi sử dụng.","Không để sản phẩm tiếp xúc trực tiếp với nước khi chưa pha.","Để xa tầm tay trẻ em và vật nuôi.","Không bảo quản gần thực phẩm, nguồn nước sinh hoạt hoặc hóa chất không tương thích.","Lắc đều trước khi sử dụng."]'::jsonb, 'Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"NPK 10-4-4 K4P","xuatXu":"Việt Nam","dang":"Dạng lỏng","congDung":"Ra rễ, đẻ nhánh, hạ phèn","baoQuan":"Nơi khô ráo, lắc đều trước dùng"}'::jsonb, '[{"icon":"Sprout","title":"Ra rễ mạnh, bộ rễ khỏe","text":"Hỗ trợ lúa phát triển bộ rễ tốt, giúp cây hấp thu dinh dưỡng hiệu quả hơn."},{"icon":"Leaf","title":"Đẻ nhánh, nở bụi nhanh","text":"Góp phần kích thích cây lúa đẻ nhánh sớm và nở bụi đồng đều, cứng cây."},{"icon":"Shield","title":"Giải độc, hạ phèn","text":"Hỗ trợ cây trong điều kiện đất phèn mặn, giúp cây chịu đựng tốt hơn."},{"icon":"Zap","title":"Xanh mướt, hạn chế vàng lá","text":"Góp phần giữ lá xanh mướt, hạn chế hiện tượng vàng lá và vàng chóp."}]'::jsonb, '[{"icon":"Sprout","title":"Lúa mới sạ","desc":"Phù hợp giai đoạn đầu sau sạ, hỗ trợ cây bén rễ và ra rễ nhanh."},{"icon":"Leaf","title":"Đẻ nhánh chậm","desc":"Hỗ trợ khi lúa đẻ nhánh chậm hoặc nở bụi kém so với kỳ vọng."},{"icon":"AlertCircle","title":"Đất phèn, mặn","desc":"Góp phần giải độc và hỗ trợ cây trong điều kiện đất phèn hoặc nhiễm mặn."},{"icon":"Sun","title":"Cây yếu, lá nhạt màu","desc":"Phù hợp khi cây lúa yếu, lá xanh nhạt hoặc sinh trưởng không đều."},{"icon":"Zap","title":"Sau stress ngập/hạn","desc":"Hỗ trợ cây phục hồi sau khi gặp điều kiện bất thuận như ngập úng, hạn hán."}]'::jsonb, '{"nhomSanPham":"Phân bón rễ / NPK","quyCach":"Chai 250ml","dangSanPham":"Dạng lỏng (nước)","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'vo-gao-nhanh', 'Vô Gạo Nhanh', 'phan-bon-la', '["lua"]'::jsonb, 'Chai 250ml', 'nuoc', 83000, null,
  '/products/cards/vo-gao-nhanh-card.png', '["/products/vo-gao-nhanh/gallery/img-1.png","/products/vo-gao-nhanh/gallery/img-2.png","/products/vo-gao-nhanh/gallery/img-3.png","/products/vo-gao-nhanh/gallery/img-4.png","/products/vo-gao-nhanh/gallery/img-5.png","/products/vo-gao-nhanh/gallery/img-6.png","/products/vo-gao-nhanh/gallery/img-7.png","/products/vo-gao-nhanh/gallery/img-8.png","/products/vo-gao-nhanh/gallery/img-9.png","/products/vo-gao-nhanh/gallery/img-10.png"]'::jsonb, 'Phân bón lá chuyên dùng cho lúa, giúp xanh dày lá, chắc cứng cổ cây, hạt to sáng bóng, hạn chế đổ ngã.', 'Phân bón hỗn hợp NPK - phân bón lá LM 17', 'Cây lương thực: 12-15ml/1.000m²/lần, bón vào thời kỳ đẻ nhánh và phân hóa đòng, hoa. Cây công nghiệp, ăn trái: 150-200ml/gốc/lần, bón vào đầu, giữa và sau mùa mưa. Giai đoạn làm bông: pha 250ml/200 lít nước. Giai đoạn mang trái: pha 150-200ml/200 lít nước, tưới vào khu vực mầm hoa non mới hình thành.', '["xanh-la","nuoi-trai","duong-cay"]'::jsonb, '["moi","ban-chay"]'::jsonb, true,
  'Vô Gạo Nhanh là phân bón NPK dạng lỏng (Phân bón lúa LM 17), chuyên dùng cho cây lúa. Sản phẩm hỗ trợ lá xanh dày, cứng cổ cây, trổ đòng thoát và giúp hạt lúa to đều, sáng bóng, ngăn chặn nguy cơ đổ ngã.

Sản phẩm phù hợp sử dụng trong nhiều giai đoạn sinh trưởng của cây lúa — từ đẻ nhánh, làm đòng, trổ bông đến giai đoạn vào chắc hạt — giúp nâng cao chất lượng và năng suất lúa gạo.', '[{"label":"Loại phân bón","value":"NPK hỗn hợp — Phân bón lúa LM 17"}]'::jsonb, 'Thành phần chi tiết theo công bố trên bao bì sản phẩm. Vui lòng tham khảo nhãn chai trước khi sử dụng.', '["Hỗ trợ lá xanh dày, tăng diện tích và hiệu quả quang hợp.","Góp phần chín cứng cổ cây, tăng độ cứng thân và hạn chế đổ ngã.","Hỗ trợ trổ đòng đồng loạt, thoát đòng nhanh và đồng đều trong ruộng.","Góp phần tạo hạt to đều, sáng bóng và tăng tỷ lệ vào chắc.","Hỗ trợ nâng cao năng suất lúa trong điều kiện canh tác bình thường."]'::jsonb, '["Lắc đều chai Vô Gạo Nhanh trước khi sử dụng.","Pha với nước sạch theo liều lượng khuyến cáo trên bao bì sản phẩm.","Phun đều lên lá hoặc tưới vào gốc tùy theo giai đoạn sinh trưởng.","Sử dụng đúng thời điểm (đẻ nhánh, làm đòng, trổ bông) để đạt hiệu quả tối ưu.","Tránh phun khi trời mưa hoặc nắng gắt trong ngày."]'::jsonb, '[{"crop":"Cây lương thực (phun lá)","dosage":"12–15ml / 1.000m² / lần, giai đoạn đẻ nhánh và phân hóa đòng"},{"crop":"Cây công nghiệp, ăn trái","dosage":"150–200ml / gốc / lần, đầu, giữa và sau mùa mưa"},{"crop":"Giai đoạn làm bông","dosage":"Pha 250ml / 200 lít nước"},{"crop":"Giai đoạn mang trái","dosage":"Pha 150–200ml / 200 lít nước"}]'::jsonb,
  '["Bảo quản nơi khô ráo, thoáng mát.","Tránh ánh nắng trực tiếp.","Đậy kín nắp sau khi mở hoặc sau khi sử dụng.","Không để sản phẩm tiếp xúc trực tiếp với nước khi chưa pha.","Để xa tầm tay trẻ em và vật nuôi.","Không bảo quản gần thực phẩm, nguồn nước sinh hoạt hoặc hóa chất không tương thích.","Lắc đều trước khi sử dụng."]'::jsonb, 'Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"NPK (Phân bón lúa LM 17)","xuatXu":"Việt Nam","dang":"Dạng lỏng","congDung":"Xanh lá, cứng cây, vào gạo","baoQuan":"Nơi khô ráo, lắc đều trước dùng"}'::jsonb, '[{"icon":"Leaf","title":"Lá xanh dày, quang hợp tốt","text":"Hỗ trợ lá xanh dày, tăng hiệu quả quang hợp và tích lũy dinh dưỡng cho cây lúa."},{"icon":"Shield","title":"Cứng cổ cây, ngăn đổ ngã","text":"Góp phần chín cứng cổ cây, hạn chế tình trạng đổ ngã và thất thoát năng suất."},{"icon":"Sun","title":"Trổ đồng loạt, thoát đòng nhanh","text":"Hỗ trợ trổ bông đồng đều trong toàn ruộng, thoát đòng nhanh và thuận lợi."},{"icon":"Zap","title":"Hạt to đều, sáng bóng","text":"Góp phần giúp hạt lúa vào chắc đều, to sáng và tăng tỷ lệ thương phẩm."}]'::jsonb, '[{"icon":"Sun","title":"Giai đoạn làm đòng","desc":"Phù hợp để sử dụng trong giai đoạn lúa làm đòng, nuôi đòng và trổ bông."},{"icon":"Leaf","title":"Lá mỏng, nhạt màu","desc":"Hỗ trợ khi lá lúa mỏng, màu nhạt hoặc quang hợp kém hiệu quả."},{"icon":"Shield","title":"Cây dễ đổ ngã","desc":"Phù hợp khi cây lúa có thân yếu hoặc ruộng có nguy cơ đổ ngã cao."},{"icon":"Zap","title":"Hạt vào chắc chậm","desc":"Hỗ trợ giai đoạn hạt vào chắc chậm hoặc tỷ lệ lép cao hơn kỳ vọng."},{"icon":"AlertCircle","title":"Ruộng trổ không đều","desc":"Góp phần hỗ trợ ruộng trổ bông đồng loạt và thoát đòng thuận lợi hơn."}]'::jsonb, '{"nhomSanPham":"Phân bón lá / NPK","quyCach":"Chai 250ml","dangSanPham":"Dạng lỏng (nước)","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'lun-cay-ruoc-dong', 'Lùn Cây - Rước Đòng', 'npk', '["lua"]'::jsonb, 'Chai 250ml', 'nuoc', 87000, null,
  '/products/cards/lun-cay-ruoc-dong-card.png', '["/products/lun-cay-ruoc-dong/img-1.jpg","/products/lun-cay-ruoc-dong/img-2.jpg","/products/lun-cay-ruoc-dong/img-3.jpg","/products/lun-cay-ruoc-dong/img-4.jpg","/products/lun-cay-ruoc-dong/img-5.jpg","/products/lun-cay-ruoc-dong/img-6.jpg","/products/lun-cay-ruoc-dong/img-7.jpg"]'::jsonb, 'Phân bón NPK chuyên dùng cho lúa, giúp lùn cây cứng thân, dưỡng đòng mập đòng, trổ thoát đồng loạt.', 'Đạm tổng số (N): 4%; Lân hữu hiệu (P2O5): 12%; Kali hữu hiệu (K2O): 10%; Độ ẩm: 5%; Tỷ trọng (dạng lỏng): 1,2', 'Cây lương thực: 12-15 lít dung dịch/1.000m²/lần, bón vào thời kỳ đẻ nhánh và phân hóa đòng, hoa. Cây công nghiệp, ăn trái: 150-200ml/gốc/lần, bón vào đầu, giữa và sau mùa mưa. Giai đoạn làm bông: pha 250ml/200 lít nước. Giai đoạn mang trái: pha 150-200ml/200 lít nước, sử dụng khi các mầm đọt non mới hình thành.', '["duong-cay","ra-hoa","nuoi-trai"]'::jsonb, '["ban-chay"]'::jsonb, true,
  'Lùn Cây - Rước Đòng là phân bón NPK dạng lỏng (Phân bón Lùm 12), chuyên dùng cho cây lúa trong giai đoạn làm đòng và trổ bông. Sản phẩm hỗ trợ ngắn lóng, cứng thân, dưỡng đòng mập và kích thích lúa trổ đồng loạt.

Phù hợp cho vùng canh tác lúa có điều kiện dễ đổ ngã hoặc giai đoạn trổ bông gặp trở ngại. Sản phẩm được phát triển để hỗ trợ tối ưu hiệu quả vụ lúa trong giai đoạn quyết định năng suất.', '[{"label":"Đạm tổng số (N)","value":"4%"},{"label":"Lân hữu hiệu (P₂O₅)","value":"12%"},{"label":"Kali hữu hiệu (K₂O)","value":"10%"},{"label":"Độ ẩm (dạng rắn)","value":"5%"},{"label":"Tỷ trọng (dạng lỏng)","value":"1,2"}]'::jsonb, 'Phân bón NPK — Phân bón Lùm 12. Thông tin theo công bố trên bao bì sản phẩm.', '["Hỗ trợ ngắn lóng, lùn cây và cứng thân lúa để hạn chế đổ ngã.","Góp phần dưỡng đòng, nuôi tim đen và giúp đòng mập khỏe.","Hỗ trợ lúa trổ bông đồng loạt và thoát đòng thuận lợi hơn.","Góp phần tăng số lượng hạt trên bông và cải thiện tỷ lệ chắc hạt.","Hỗ trợ cây đứng lá, mướt lá và hạn chế tình trạng đổ ngã trong giai đoạn trổ."]'::jsonb, '["Lắc đều chai Lùn Cây - Rước Đòng trước khi sử dụng.","Pha với nước sạch theo liều lượng trên bao bì sản phẩm.","Sử dụng đúng thời điểm cây lúa bắt đầu làm đòng hoặc theo hướng dẫn kỹ thuật.","Phun lên lá hoặc tưới gốc tùy theo giai đoạn và loại cây.","Tránh phun khi trời mưa hoặc nhiệt độ quá cao."]'::jsonb, '[{"crop":"Cây lương thực","dosage":"12–15 lít dung dịch / 1.000m² / lần, giai đoạn đẻ nhánh và phân hóa đòng"},{"crop":"Cây công nghiệp, ăn trái","dosage":"150–200ml / gốc / lần, đầu, giữa và sau mùa mưa"},{"crop":"Giai đoạn làm bông","dosage":"Pha 250ml / 200 lít nước"},{"crop":"Giai đoạn mang trái","dosage":"Pha 150–200ml / 200 lít nước, khi mầm đọt non mới hình thành"}]'::jsonb,
  '["Bảo quản nơi khô ráo, thoáng mát.","Tránh ánh nắng trực tiếp.","Đậy kín nắp sau khi mở hoặc sau khi sử dụng.","Không để sản phẩm tiếp xúc trực tiếp với nước khi chưa pha.","Để xa tầm tay trẻ em và vật nuôi.","Không bảo quản gần thực phẩm, nguồn nước sinh hoạt hoặc hóa chất không tương thích.","Lắc đều trước khi sử dụng."]'::jsonb, 'Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"NPK 4-12-10 (Lùm 12)","xuatXu":"Việt Nam","dang":"Dạng lỏng","congDung":"Lùn cây, cứng thân, rước đòng","baoQuan":"Nơi khô ráo, lắc đều trước dùng"}'::jsonb, '[{"icon":"Shield","title":"Ngắn lóng, cứng thân","text":"Hỗ trợ ngắn lóng và cứng thân giúp cây lúa vững chắc, hạn chế đổ ngã."},{"icon":"Leaf","title":"Nuôi đòng mập, khỏe","text":"Góp phần dưỡng đòng và nuôi tim đen giúp đòng mập, khỏe và đầy đặn hơn."},{"icon":"Sun","title":"Trổ bông đồng loạt","text":"Hỗ trợ lúa trổ bông đồng đều trong toàn ruộng và thoát đòng thuận lợi."},{"icon":"Zap","title":"Tăng số hạt/bông","text":"Góp phần cải thiện số hạt trên bông và tỷ lệ hạt chắc cho năng suất tốt hơn."}]'::jsonb, '[{"icon":"Shield","title":"Cây dễ đổ ngã","desc":"Phù hợp khi lúa có thân yếu, lóng dài hoặc ruộng có nguy cơ đổ ngã cao."},{"icon":"Sun","title":"Giai đoạn làm đòng","desc":"Sử dụng đúng thời điểm cây lúa bắt đầu làm đòng để đạt hiệu quả tốt nhất."},{"icon":"Leaf","title":"Đòng yếu, ít hạt","desc":"Hỗ trợ khi đòng phát triển yếu hoặc số hạt/bông thấp hơn kỳ vọng."},{"icon":"AlertCircle","title":"Trổ không đồng đều","desc":"Góp phần khắc phục tình trạng lúa trổ không đều hoặc thoát đòng gặp trở ngại."},{"icon":"Zap","title":"Muốn nâng năng suất","desc":"Phù hợp cho ruộng muốn cải thiện tỷ lệ chắc hạt và năng suất vụ lúa."}]'::jsonb, '{"nhomSanPham":"Phân bón NPK","quyCach":"Chai 250ml","dangSanPham":"Dạng lỏng (nước)","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'loang-trai-tham-sau', 'Loang Trải Thấm Sâu', 'phan-bon-re', '["lua","rau-mau","cay-an-trai","hoa-kieng","cay-cong-nghiep"]'::jsonb, 'Chai 100ml', 'nuoc', 84550, 89000,
  '/products/cards/loang-trai-tham-sau-card.png', '["/products/loang-trai-tham-sau/gallery/img-1.png","/products/loang-trai-tham-sau/gallery/img-2.png","/products/loang-trai-tham-sau/gallery/img-3.png","/products/loang-trai-tham-sau/gallery/img-4.png","/products/loang-trai-tham-sau/gallery/img-5.png","/products/loang-trai-tham-sau/gallery/img-6.png","/products/loang-trai-tham-sau/gallery/img-7.png","/products/loang-trai-tham-sau/gallery/img-8.png","/products/loang-trai-tham-sau/gallery/img-9.png"]'::jsonb, 'Chất hỗ trợ lan trải và thấm sâu, giúp phân bón thẩm thấu đều vào đất và rễ cây, tăng hiệu quả hấp thu dưỡng chất.', 'Chất hoạt động bề mặt sinh học, chất lan trải hữu cơ', 'Pha cùng dung dịch phân bón hoặc thuốc bảo vệ thực vật theo tỉ lệ khuyến cáo trên nhãn. Sử dụng khi tưới gốc hoặc phun lá để tăng hiệu quả thẩm thấu và hấp thu.', '["ra-re","cai-tao-dat","phuc-hoi-cay-yeu"]'::jsonb, '["ban-chay"]'::jsonb, true,
  'Loang Trải Thấm Sâu là chế phẩm dùng trong nông nghiệp (Siêu thấm thấu 30SL), được thiết kế để sử dụng kết hợp cùng phân bón hoặc thuốc bảo vệ thực vật. Sản phẩm hỗ trợ tăng khả năng bám dính, lan trải đều và thấm sâu trên bề mặt lá và cây trồng.

Khi phối hợp với phân bón hoặc BVTV, sản phẩm giúp dung dịch tiếp xúc đều hơn trên toàn bề mặt lá, thấm sâu vào mô cây và tăng hiệu quả hấp thu — góp phần giúp phân bón và thuốc phát huy tốt hơn.', '[{"label":"Surfactant C10 Alcohol Ethoxylate","value":"30%"},{"label":"Phụ gia đặc biệt","value":"Vừa đủ 70%"},{"label":"Tỷ trọng (dạng lỏng)","value":"1,1"},{"label":"Thể tích thực","value":"100ml"},{"label":"Số TCCS","value":"01:2024/LOANGTRAI-TS"}]'::jsonb, 'Chế phẩm dùng trong nông nghiệp — Siêu thấm thấu 30SL. Thông tin theo công bố trên bao bì sản phẩm.', '["Tăng khả năng bám dính của dung dịch phân bón/thuốc BVTV trên bề mặt lá.","Hỗ trợ lan trải đều, giúp dung dịch phủ đều hơn trên toàn bộ bề mặt cây.","Kích nở khí không, hỗ trợ thấm sâu vào mô lá và cơ quan hấp thu của cây.","Góp phần tăng hiệu quả hấp thu phân bón và thuốc BVTV.","Giúp tiết kiệm lượng phân bón/thuốc nhờ phân bố đều hơn trên cây trồng.","An toàn cho cây trồng và môi trường khi sử dụng đúng liều lượng."]'::jsonb, '["Lắc đều chai Loang Trải Thấm Sâu trước khi sử dụng.","Pha 100ml cho mỗi 300 lít nước (hoặc theo hướng dẫn trên bao bì).","Phối hợp cùng dung dịch phân bón hoặc thuốc BVTV cần sử dụng.","Phun ướt đều toàn bộ cây trồng — mặt lá, mặt dưới lá và thân cây.","Sử dụng vào buổi sáng sớm hoặc chiều mát để tăng hiệu quả hấp thu."]'::jsonb, '[{"crop":"Phối với phân bón / thuốc BVTV","dosage":"100ml / 300 lít nước, phun ướt đều cây trồng"}]'::jsonb,
  '["Bảo quản nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.","Đậy kín nắp chai sau khi sử dụng.","Tránh xa tầm tay trẻ em và nguồn thực phẩm.","Sử dụng vào buổi sáng sớm hoặc chiều mát.","Không bảo quản gần nguồn nước sinh hoạt hoặc hóa chất không tương thích."]'::jsonb, 'Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"Surfactant C10 AE 30%","xuatXu":"Việt Nam","dang":"Dung dịch (lỏng)","congDung":"Tăng bám dính, thấm sâu","baoQuan":"Nơi khô ráo, đậy kín sau dùng"}'::jsonb, '[{"icon":"Droplets","title":"Tăng bám dính","text":"Hỗ trợ phân bón và thuốc BVTV bám chặt hơn trên bề mặt lá, giảm trôi rửa do mưa."},{"icon":"Zap","title":"Loang trải đều","text":"Giúp dung dịch phủ đều toàn bộ bề mặt cây, không bỏ sót vùng tiếp xúc quan trọng."},{"icon":"Sprout","title":"Thấm sâu hiệu quả","text":"Hỗ trợ dung dịch thấm sâu vào mô lá và cơ quan hấp thu của cây trồng."},{"icon":"Leaf","title":"Tiết kiệm chi phí","text":"Giúp tối ưu hiệu quả của phân bón và thuốc đã dùng, có thể giảm lượng cần thiết."}]'::jsonb, '[{"icon":"Droplets","title":"Phun trong mùa mưa","desc":"Giúp tăng bám dính của dung dịch khi thời tiết dễ bị rửa trôi."},{"icon":"Leaf","title":"Lá trơn, khó thấm","desc":"Phù hợp với các loại cây có bề mặt lá trơn, dung dịch dễ chảy đi."},{"icon":"Zap","title":"Muốn tăng hiệu quả","desc":"Khi muốn tối ưu hiệu quả của phân bón hoặc thuốc BVTV đang sử dụng."},{"icon":"Sun","title":"Phun diện tích lớn","desc":"Phù hợp khi phun trên diện tích lớn, cần đảm bảo phủ đều mà không tăng lượng thuốc."},{"icon":"Shield","title":"Cây hấp thu kém","desc":"Hỗ trợ khi cây có dấu hiệu hấp thu chậm hoặc phân bón không phát huy hiệu quả."}]'::jsonb, '{"nhomSanPham":"Chế phẩm nông nghiệp","quyCach":"Chai 100ml","dangSanPham":"Dung dịch lỏng (30SL)","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'robust', 'Robust Giải Độc Tố Đất', 'huu-co', '["cay-an-trai","cay-cong-nghiep","rau-mau"]'::jsonb, 'Chai 1 Lít', 'nuoc', 117000, 130000,
  '/products/robust/img-1.png', '["/products/robust/gallery/img-1.png","/products/robust/gallery/img-2.png","/products/robust/gallery/img-3.png","/products/robust/gallery/img-4.png","/products/robust/gallery/img-5.png","/products/robust/gallery/img-6.png","/products/robust/gallery/img-7.png","/products/robust/gallery/img-8.png","/products/robust/gallery/img-9.png"]'::jsonb, 'Chế phẩm sinh học giải độc tố đất, kháng khuẩn, giữ ẩm, khử phèn và tạo hệ vi sinh vật có lợi phát triển.', 'VSV phân giải Xenllulo 1x10⁸ CFU/ml; Nguyên liệu: chuối, trứng, sữa; Vi sinh chuyên dùng: Bacillus, Trichoderma, Enzyme', 'Cây thân gỗ (sầu riêng, chè, cà phê): 1 lít/200-400 lít nước. Cây rau màu, cây thân dây (hồ tiêu, chanh dây, khổ qua, bầu bí, dưa, khoai lang, các loại đậu...): 1 lít/400-600 lít nước. Tưới quanh gốc vào sáng sớm hoặc chiều mát, tưới nước cho đất ẩm trước khi tưới vi sinh để tạo đường dẫn.', '["cai-tao-dat","phuc-hoi-cay-yeu","ra-re"]'::jsonb, '["moi"]'::jsonb, true,
  'ROBUST Giải Độc Tố Đất là chế phẩm sinh học giúp giải độc tố trong đất, cải tạo hệ vi sinh, giữ ẩm và phục hồi bộ rễ khỏe mạnh. Giải pháp sinh học an toàn cho cây trồng và đất canh tác lâu dài, hữu cơ an toàn — lành tính — phù hợp sử dụng cho nhiều loại cây trồng.

Sản phẩm phân giải các độc tố như kim loại nặng, hóa chất tồn dư trong đất, tạo hệ vi sinh làm đất tơi xốp, ổn định pH và có thể dùng để ủ rơm rạ, cám gạo, phân chuồng thành phân bón.', '[{"label":"VSV phân giải Xenllulo","value":"1x10⁸ CFU/ml"},{"label":"Nguyên liệu","value":"Chuối, trứng, sữa"},{"label":"Vi sinh chuyên dùng","value":"Bacillus, Trichoderma, Enzyme"},{"label":"Thể tích thực","value":"1 lít"}]'::jsonb, 'Thông tin thành phần được trình bày theo công bố trên bao bì sản phẩm.', '["Cải tạo đất: phân giải độc tố gồm các chất có hại như kim loại nặng, hóa chất tồn dư trong đất.","Tạo hệ vi sinh làm đất tơi xốp.","Ổn định pH đất (là hiệu ứng phụ đi kèm, không thay thế sản phẩm chuyên biệt cân bằng pH).","Dùng để ủ rơm rạ, cám gạo, phân chuồng... làm phân bón.","Giữ ẩm cho đất, hỗ trợ phục hồi bộ rễ khỏe mạnh."]'::jsonb, '["Lắc đều chai Robust trước khi pha.","Pha theo liều lượng ở bảng dưới tùy nhóm cây trồng.","Tưới nước trước cho cây ẩm ướt nhằm tạo đường dẫn cho vi sinh thẩm thấu.","Tưới đều quanh gốc vào sáng sớm hoặc chiều mát.","Không pha chung với thuốc trừ sâu, thuốc có gốc đồng."]'::jsonb, '[{"crop":"Cây thân gỗ (sầu riêng, chè, cà phê)","dosage":"1 lít / 200–400 lít nước, tưới quanh gốc"},{"crop":"Cây rau màu, cây thân dây (hồ tiêu, chanh dây, khổ qua, bầu bí, dưa, khoai lang, các loại đậu...)","dosage":"1 lít / 400–600 lít nước, tưới quanh gốc"}]'::jsonb,
  '["Nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.","Đậy nắp sau khi sử dụng.","Lắc đều trước khi pha.","Hạn sử dụng: 24 tháng kể từ ngày sản xuất, 6 tháng sau khi mở nắp.","Sau khi pha với nước: không để dung dịch quá 7 ngày."]'::jsonb, 'Không pha chung với thuốc trừ sâu hoặc thuốc có gốc đồng. Có thể điều chỉnh liều lượng phù hợp với tình trạng cây trồng, thổ nhưỡng đất canh tác và kinh nghiệm thực tế của người trồng.

Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"VSV Xenllulo, Bacillus, Trichoderma","xuatXu":"Việt Nam","quyCach":"Chai 1 Lít","dang":"Dạng lỏng","congDung":"Giải độc đất, khử phèn, tạo hệ vi sinh","baoQuan":"Nơi khô ráo, đậy nắp sau dùng"}'::jsonb, '[{"icon":"Shield","title":"Giải độc tố đất","text":"Phân giải độc tố như kim loại nặng, hóa chất tồn dư giúp đất sạch và an toàn hơn."},{"icon":"Droplets","title":"Giữ ẩm, khử phèn","text":"Giúp đất giữ ẩm tốt hơn và cải thiện môi trường đất chua phèn."},{"icon":"Sprout","title":"Tạo hệ vi sinh có lợi","text":"Góp phần tạo hệ vi sinh làm đất tơi xốp, ổn định pH và thông thoáng hơn."},{"icon":"Leaf","title":"Ủ phân hữu cơ","text":"Có thể dùng để ủ rơm rạ, cám gạo, phân chuồng... thành phân bón hữu cơ."}]'::jsonb, '[{"icon":"AlertCircle","title":"Đất bạc màu, chai cứng","desc":"Phù hợp cho đất bạc màu, nhiễm phèn hoặc chai cứng sau nhiều vụ dùng hóa chất."},{"icon":"Sprout","title":"Đất tồn dư hóa chất","desc":"Hỗ trợ phân giải kim loại nặng và hóa chất tồn dư trong đất canh tác."},{"icon":"Shield","title":"Trước khi vào vụ mới","desc":"Thích hợp cải tạo đất trước khi xuống giống vụ mới, đặc biệt vùng đất phèn, mặn."},{"icon":"Droplets","title":"Đất khô hạn cục bộ","desc":"Hỗ trợ giữ ẩm cho đất trong điều kiện khô hạn quanh vùng rễ."},{"icon":"Leaf","title":"Cần ủ phân hữu cơ","desc":"Phù hợp khi cần ủ rơm rạ, cám gạo hoặc phân chuồng thành phân bón."}]'::jsonb, '{"nhomSanPham":"Chế phẩm sinh học cải tạo đất","quyCach":"Chai 1 Lít","dangSanPham":"Dung dịch lỏng","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'lasting-khang-nam-tuyen-trung', 'Lasting Kháng Nấm - Tuyến Trùng', 'phan-bon-re', '["cay-an-trai","cay-cong-nghiep","rau-mau"]'::jsonb, 'Chai 1 Lít', 'nuoc', 117000, 130000,
  '/products/lasting-khang-nam-tuyen-trung/img-1.png', '["/products/lasting-khang-nam-tuyen-trung/gallery/img-1.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-2.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-3.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-4.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-5.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-6.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-7.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-8.png","/products/lasting-khang-nam-tuyen-trung/gallery/img-9.png"]'::jsonb, 'Chế phẩm sinh học giúp kiểm soát nấm bệnh, tuyến trùng, phát triển bộ rễ khỏe, khử phèn và cải tạo đất.', 'VSV phân giải Xenllulo 1x10⁸ CFU/ml; Vi sinh vật có lợi: Bacillus, Trichoderma, Enzyme; Thảo dược truyền thống', 'Cây thân gỗ (sầu riêng, chè, cà phê): 1 lít/100-200 lít nước, tưới lá và quanh gốc. Cây rau màu, cây thân dây (hồ tiêu, chanh dây, khổ qua, bầu bí, dưa, khoai lang, các loại đậu...): 1 lít/200-400 lít nước, tưới lá và quanh gốc. Tưới vào sáng sớm hoặc chiều mát.', '["ra-re","cai-tao-dat","phuc-hoi-cay-yeu"]'::jsonb, '["moi"]'::jsonb, true,
  'LASTING Kháng Nấm – Tuyến Trùng hỗ trợ kiểm soát nấm bệnh và tuyến trùng, đồng thời giúp cây phát triển bộ rễ khỏe, phục hồi sau giai đoạn bị ảnh hưởng và cải thiện môi trường đất. Hữu cơ an toàn — lành tính — phù hợp sử dụng cho nhiều loại cây trồng.

Sản phẩm giúp tăng sức đề kháng cho cây trồng, chống các chủng nấm và vi khuẩn có hại như nấm Phytophthora, nấm Fusarium và tuyến trùng gây nứt thân xì mủ, nấm phấn hồng, đồng thời ngăn ngừa bệnh hại như sùng, hà cho cây khoai lang.', '[{"label":"VSV phân giải Xenllulo","value":"1x10⁸ CFU/ml"},{"label":"Vi sinh vật có lợi","value":"Bacillus, Trichoderma, Enzyme"},{"label":"Thảo dược truyền thống","value":"Có"},{"label":"Thể tích thực","value":"1 lít"}]'::jsonb, 'Thông tin thành phần được trình bày theo công bố trên bao bì sản phẩm.', '["Tăng sức đề kháng cho cây trồng, chống các chủng nấm và vi khuẩn có hại như nấm Phytophthora, nấm Fusarium.","Kháng tuyến trùng gây nứt thân xì mủ, nấm phấn hồng.","Giúp cây có nội vi sinh chống lại các điều kiện thời tiết bất thường.","Ngăn ngừa bệnh hại như sùng, hà cho cây khoai lang.","Hỗ trợ phát triển bộ rễ khỏe, khử phèn và cải tạo đất."]'::jsonb, '["Lắc đều chai Lasting trước khi pha.","Pha theo liều lượng ở bảng dưới tùy nhóm cây trồng.","Tưới ướt đẫm vùng bị nấm/tuyến trùng, nứt thân, xì mủ để vi sinh dễ lưu dẫn.","Dưới mặt đất, dùng dụng cụ hỗ trợ (cây ba chĩa) xăm đều quanh gốc và dưới tán lá để tạo đường dẫn cho vi sinh thẩm thấu.","Cây thân gỗ không cần cạo vỏ khi tưới, chỉ cần tưới đẫm vùng cổ rễ, nơi nứt thân xì mủ và dưới tán lá.","Tưới vào sáng sớm hoặc chiều mát. Không pha chung với thuốc trừ sâu, thuốc có gốc đồng."]'::jsonb, '[{"crop":"Cây thân gỗ (sầu riêng, chè, cà phê)","dosage":"1 lít / 100–200 lít nước, tưới lá và xung quanh gốc"},{"crop":"Cây rau màu, cây thân dây (hồ tiêu, chanh dây, khổ qua, bầu bí, dưa, khoai lang, các loại đậu...)","dosage":"1 lít / 200–400 lít nước, tưới lá và xung quanh gốc"}]'::jsonb,
  '["Nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.","Đậy nắp sau khi sử dụng.","Lắc đều trước khi pha.","Hạn sử dụng: 24 tháng kể từ ngày sản xuất, 6 tháng sau khi mở nắp.","Sau khi pha với nước: không để dung dịch quá 7 ngày."]'::jsonb, 'Không pha chung với thuốc trừ sâu hoặc thuốc có gốc đồng. Có thể điều chỉnh liều lượng phù hợp với tình trạng cây trồng, thổ nhưỡng đất canh tác và kinh nghiệm thực tế của người trồng.

Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"VSV Xenllulo, Bacillus, Trichoderma","xuatXu":"Việt Nam","quyCach":"Chai 1 Lít","dang":"Dạng lỏng","congDung":"Kháng nấm, tuyến trùng, bật rễ","baoQuan":"Nơi khô ráo, đậy nắp sau dùng"}'::jsonb, '[{"icon":"Shield","title":"Kháng nấm, tuyến trùng","text":"Chống các chủng nấm Phytophthora, Fusarium và tuyến trùng gây nứt thân xì mủ."},{"icon":"Droplets","title":"Khử phèn, cải tạo đất","text":"Góp phần cải thiện môi trường đất chua phèn, tạo điều kiện tốt cho cây trồng."},{"icon":"Sprout","title":"Phát triển bộ rễ khỏe","text":"Hỗ trợ cây phát triển bộ rễ khỏe, phục hồi sau giai đoạn bị ảnh hưởng."},{"icon":"Leaf","title":"Tăng sức đề kháng","text":"Giúp cây có nội vi sinh chống lại các điều kiện thời tiết bất thường."}]'::jsonb, '[{"icon":"AlertCircle","title":"Nứt thân, xì mủ","desc":"Phù hợp khi cây (đặc biệt sầu riêng) có dấu hiệu nứt thân, xì mủ do nấm hoặc tuyến trùng."},{"icon":"Shield","title":"Nhiễm nấm Phytophthora, Fusarium","desc":"Hỗ trợ kiểm soát các chủng nấm gây hại phổ biến trên cây ăn trái, cây công nghiệp."},{"icon":"Sprout","title":"Bộ rễ suy yếu","desc":"Phù hợp khi cây cần phục hồi bộ rễ sau giai đoạn bị nấm, tuyến trùng tấn công."},{"icon":"Leaf","title":"Đất nhiễm phèn","desc":"Hỗ trợ khử phèn và cải tạo môi trường đất cho cây trồng."},{"icon":"Droplets","title":"Khoai lang bị sùng, hà","desc":"Ngăn ngừa bệnh hại như sùng, hà thường gặp trên cây khoai lang."}]'::jsonb, '{"nhomSanPham":"Chế phẩm sinh học bảo vệ rễ / cải tạo đất","quyCach":"Chai 1 Lít","dangSanPham":"Dung dịch lỏng","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

insert into products (
  slug, name, category, crop_types, package_unit, form, price, original_price,
  image, images, short_description, ingredients, usage_instructions, usage_needs, tags, in_stock,
  overview, ingredient_items, ingredient_note, benefit_items, usage_steps, dosage_table,
  storage_items, warning_note, quick_info, benefits, suitable_when, specification
) values (
  'bumper-duong', 'Bumper Dưỡng Trái', 'npk', '["lua","rau-mau","cay-an-trai","cay-cong-nghiep"]'::jsonb, 'Chai 1 Lít', 'nuoc', 117000, 130000,
  '/products/bumper-duong/img-1.png', '["/products/bumper-duong/gallery/img-1.png","/products/bumper-duong/gallery/img-2.png","/products/bumper-duong/gallery/img-3.png","/products/bumper-duong/gallery/img-4.png","/products/bumper-duong/gallery/img-5.png","/products/bumper-duong/gallery/img-6.png","/products/bumper-duong/gallery/img-7.png","/products/bumper-duong/gallery/img-8.png","/products/bumper-duong/gallery/img-9.png","/products/bumper-duong/gallery/img-10.png"]'::jsonb, 'Chế phẩm sinh học dưỡng trái giúp trái lớn nhanh, căng bóng, nặng ký, tăng độ ngọt tự nhiên và đồng đều.', 'VSV phân giải Xenllulo 0,1x10⁸ CFU/ml; Nguyên liệu: đạm tôm, bánh dầu, rong biển, nha đam; Vi sinh chuyên dùng: Bacillus, Trichoderma, Enzyme', 'Cây trồng lâu năm (sầu riêng, điều, chè, cà phê, ca cao, xoài, bưởi, thanh long...): 1 lít/200-400 lít nước, tưới gốc 10-15 lít/cây trưởng thành (5-10 lít/cây nhỏ), chu kỳ 15-20 ngày/lần. Cây thân dây: 1 lít/400-600 lít nước, chu kỳ 10-15 ngày/lần. Cây rau màu: 1 lít/600-800 lít nước, chu kỳ 7-10 ngày/lần.', '["nuoi-trai","duong-cay"]'::jsonb, '["moi"]'::jsonb, true,
  'BUMPER Dưỡng Trái bổ sung dưỡng chất giúp nuôi trái lớn nhanh, căng bóng, nặng ký — tăng độ ngọt tự nhiên — trái đồng đều, nâng cao giá trị nông sản. Giải pháp sinh học an toàn, hiệu quả cho cây trồng và đất canh tác lâu dài, hữu cơ an toàn — lành tính.

Chuyên dùng cho cây công nghiệp, dược liệu, cây ăn quả, cây lương thực, lúa và rau củ quả — thúc đẩy quá trình sinh trưởng, tổng hợp trao đổi chất, tăng sức đề kháng và giảm tỷ lệ thất thoát nông sản.', '[{"label":"VSV phân giải Xenllulo","value":"0,1x10⁸ CFU/ml"},{"label":"Nguyên liệu","value":"Đạm tôm, bánh dầu, rong biển, nha đam"},{"label":"Vi sinh chuyên dùng","value":"Bacillus, Trichoderma, Enzyme"},{"label":"Thể tích thực","value":"1 lít"}]'::jsonb, 'Thông tin thành phần được trình bày theo công bố trên bao bì sản phẩm.', '["Thúc đẩy quá trình sinh trưởng, tổng hợp trao đổi chất cho các loại cây và củ.","Tăng sức đề kháng, giúp cây phát triển, củ và trái to, sáng bóng, có trọng lượng.","Tăng hương vị tự nhiên, trái ngọt và đồng đều hơn.","Giảm tỷ lệ thất thoát nông sản."]'::jsonb, '["Lắc đều chai Bumper Dưỡng Trái trước khi pha.","Tưới nước trước cho cây ẩm ướt để tạo đường dẫn cho vi sinh thẩm thấu.","Pha và tưới gốc theo đúng nhóm cây, liều lượng và chu kỳ ở bảng dưới.","Tưới vào sáng sớm hoặc chiều mát.","Không pha chung với thuốc trừ sâu, thuốc có gốc đồng."]'::jsonb, '[{"crop":"Cây trồng lâu năm (sầu riêng, điều, chè, cà phê, ca cao, xoài, bưởi, thanh long...) — cây trưởng thành","dosage":"Pha 1 lít/200–400 lít nước, tưới gốc 10–15 lít dung dịch/cây, chu kỳ 15–20 ngày/lần"},{"crop":"Cây trồng lâu năm — cây vừa và nhỏ","dosage":"Pha 1 lít/200–400 lít nước, tưới gốc 5–10 lít dung dịch/cây, chu kỳ 15–20 ngày/lần"},{"crop":"Cây thân dây (hồ tiêu, chanh dây, bầu, bí, khổ qua, ớt, các loại dưa, khoai lang...)","dosage":"Pha 1 lít/400–600 lít nước, tưới gốc 50–100 lít/1.000m², chu kỳ 10–15 ngày/lần"},{"crop":"Cây rau màu (bắp cải, xà lách, các loại cải, rau thơm, cây gia vị, hành lá...)","dosage":"Pha 1 lít/600–800 lít nước, tưới gốc 40–60 lít/1.000m², chu kỳ 7–10 ngày/lần"}]'::jsonb,
  '["Nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.","Đậy nắp sau khi sử dụng.","Lắc đều trước khi pha.","Hạn sử dụng: 24 tháng kể từ ngày sản xuất, 6 tháng sau khi mở nắp.","Sau khi pha với nước: không để dung dịch quá 7 ngày."]'::jsonb, 'Không pha chung với thuốc trừ sâu hoặc thuốc có gốc đồng. Có thể điều chỉnh liều lượng phù hợp với tình trạng cây trồng, thổ nhưỡng đất canh tác và kinh nghiệm thực tế của người trồng.

Hiệu quả sử dụng sản phẩm có thể thay đổi tùy theo loại cây, tình trạng đất, điều kiện thời tiết, kỹ thuật canh tác và cách sử dụng thực tế. Khách hàng nên đọc kỹ hướng dẫn trên bao bì trước khi sử dụng.

Thông tin trên website chỉ có tính chất tham khảo và không thay thế hướng dẫn chính thức trên bao bì sản phẩm.', '{"thanhPhan":"VSV Xenllulo, đạm tôm, rong biển","xuatXu":"Việt Nam","quyCach":"Chai 1 Lít","dang":"Dạng lỏng","congDung":"Dưỡng trái, to trái, ngọt trái","baoQuan":"Nơi khô ráo, đậy nắp sau dùng"}'::jsonb, '[{"icon":"Sun","title":"To trái, căng bóng","text":"Giúp trái lớn nhanh, căng bóng, nặng ký và có trọng lượng tốt hơn."},{"icon":"Zap","title":"Tăng độ ngọt tự nhiên","text":"Hỗ trợ tổng hợp trao đổi chất giúp trái tăng hương vị và độ ngọt tự nhiên."},{"icon":"Sprout","title":"Trái đồng đều","text":"Góp phần giúp trái phát triển đồng đều trên toàn bộ cây trồng."},{"icon":"Leaf","title":"Giảm thất thoát","text":"Tăng sức đề kháng cho cây, giúp giảm tỷ lệ thất thoát nông sản."}]'::jsonb, '[{"icon":"Sun","title":"Giai đoạn nuôi trái","desc":"Phù hợp sử dụng đúng giai đoạn cây đang nuôi trái, cần bổ sung dưỡng chất."},{"icon":"Zap","title":"Trái nhỏ, chưa đều","desc":"Hỗ trợ khi trái phát triển không đều hoặc kích thước chưa đạt kỳ vọng."},{"icon":"Leaf","title":"Muốn nâng chất lượng","desc":"Phù hợp khi muốn cải thiện độ ngọt, trọng lượng và hương vị nông sản trước thu hoạch."},{"icon":"Sprout","title":"Cây ăn trái, cây lâu năm","desc":"Thích hợp cho sầu riêng, xoài, bưởi, thanh long và các cây ăn trái khác trong giai đoạn nuôi trái."},{"icon":"AlertCircle","title":"Tỷ lệ thất thoát cao","desc":"Hỗ trợ giảm tỷ lệ thất thoát nông sản nhờ tăng sức đề kháng cho cây."}]'::jsonb, '{"nhomSanPham":"Chế phẩm sinh học dưỡng trái","quyCach":"Chai 1 Lít","dangSanPham":"Dung dịch lỏng","xuatXu":"Việt Nam"}'::jsonb
)
on conflict (slug) do nothing;

-- 3 mã giảm giá đang có, không giới hạn số lần/ngày (đúng như trước đây)
insert into coupons (code, type, value, active) values
  ('QUOCANH', 'fixed', 50000, true),
  ('DUYPHONG', 'fixed', 50000, true),
  ('MERIFARM', 'percent', 5, true)
on conflict (code) do nothing;

-- Thông tin nhận tiền hiện tại
update payment_settings set
  bank_name = 'Ngân hàng MB Bank - Ngân hàng Thương mại cổ phần Quân đội',
  account_number = '952076868',
  account_holder = 'CONG TY TNHH CONG NGHE DVP-DEDITECH'
where id = 1;